name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build
        run: |
          mkdir -p dist
          GOOS=darwin GOARCH=amd64 go build -o dist/slack-tool-darwin-amd64 ./cmd/slack-tool
          GOOS=darwin GOARCH=arm64 go build -o dist/slack-tool-darwin-arm64 ./cmd/slack-tool
          GOOS=linux GOARCH=amd64 go build -o dist/slack-tool-linux-amd64 ./cmd/slack-tool
          GOOS=windows GOARCH=amd64 go build -o dist/slack-tool-windows-amd64.exe ./cmd/slack-tool

      - name: Create checksums
        run: |
          cd dist
          sha256sum * > checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
